### ISSUE TITLE
No package.json, deprecated library usage

### ISSUE THREAD

**Issue by stretch07** [cspi-git/ZeroDiscord#19]
sup.
None of these have npm package.jsons, what are we supposed to do, make them manually???
Also discord.js-client has been deprecated
Is this maintained @iUseYahoo

**Comment by iUseYahoo** [comment]
> Is this maintained

No, from my understand this repository is not maintained. @I2rys please confirm this.

**Comment by stretch07** [comment]
that just seems incredibly inconvenient
If it turns out that this repo is maintained, I'll make sure to pull request package.json files

**Comment by I2rys** [comment]
> > Is this maintained
> 
> No, from my understanding this repository is not maintained. @I2rys please confirm this. You should be installing the required packages yourself.
> 
> Example (https://github.com/hanaui-git/ZeroDiscord/tree/main/purifier) If you wanted to use the purifier you would have to run the following:
> 
> ```
> npm i recursive-readdir-async
> npm i parallel-park
> npm i chalk
> ```

This repository is maintained.

**Comment by stretch07** [comment]
But why not just include a package.json file?

**Comment by I2rys** [comment]
> But why not just include a package.json file?

It's just gonna have hard time adding the tools dependencies one by one also It's basically the same but It's all in one in installing.

**Comment by I2rys** [comment]
> Sorry I don't understand. With q package.json file with dependencies specified, you can just run npm i and everything will automatically install??

Yes It will automatically install the given dependencies using the **npm i** command.

**Comment by I2rys** [comment]
> Considering it is this simple, why don't you just add a package.json file already

Oh flip yeah I just realized that... I think an unconciouse habit. 💀

**Comment by I2rys** [comment]
@stretch07 I'll add the package.json in the next update mate. :D
