### ISSUE TITLE
How do i get the code then use it 

### ISSUE THREAD

**Issue by Luca2091** [cspi-git/ZeroDiscord#22]
I don't understand how to get the files or how to use them one I have them

**Comment by I2rys** [comment]
Hello @Luca2091, but do you have any knowledge on Git or NodeJS?

**Comment by Luca2091** [comment]
i have a bit on node js but not git

**Comment by iUseYahoo** [comment]
> I don't understand how to get the files or how to use them one I have them 

Firstly clone the repo using `git clone` or just download the repo via your browser. 

To use functions in another code file (.js) that file that you want to use functions from will need to use `module.exports` in order for you to be able to call the function, inside that code file you will see the parameters that it takes which you can use

**Comment by iUseYahoo** [comment]
> what do you mean by the second part about functions
> 
> 

[Join our discord and ping Altorx for help](https://discord.gg/MGYCnw4VET)

**Comment by I2rys** [comment]
@iUseYahoo any updates?

**Comment by iUseYahoo** [comment]
> @iUseYahoo any updates?

Solved in CSPI server.
