### ISSUE TITLE
it keeps saying softwere contains virus

### ISSUE THREAD

**Issue by zayiyn** [cspi-git/ZeroDiscord#24]
<img width="430" alt="image" src="https://github.com/cspi-git/ZeroDiscord/assets/142721692/5347c65e-9a83-43c2-afbb-0886112295ce">

**Comment by iUseYahoo** [comment]
This repo is safe to use and is being flagged falsely due to the nature of the scripts. Feel free to check it out on [https://virustotal.com](https://virustotal.com)

**Comment by letmecheatinfn** [comment]
it doesnt neccerarly say it has a virus, it says it contains a virus **or** potientially unwanted program (PUP)

this repo is comepletely safe
