### ISSUE TITLE
How do I setup?

### ISSUE THREAD

**Issue by ykcue** [cspi-git/ZeroDiscord#27]
I've been reading the issues and I'm very confused. I'm not experienced with coding or github at all. Can someone help me? My discord username is Arostotl3

**Comment by iUseYahoo** [comment]
> I've been reading the issues and I'm very confused. I'm not experienced with coding or github at all. Can someone help me? My discord username is Arostotl3

Check your discord friends requests

**Comment by I2rys** [comment]
@iUseYahoo has the problem been solved mate?

**Comment by iUseYahoo** [comment]
> @iUseYahoo has the problem been solved mate?

Solved in DMs.
