### ISSUE TITLE
Help Setting Up

### ISSUE THREAD

**Issue by aftershock4g** [cspi-git/ZeroDiscord#29]
Hello, 

I admittedly have little to no experience with coding but I'd love to start learning, in downloading this I'm having struggles getting it going. I came across these instructions - Clone this repository
Make a file called "index.js" in ZeroDiscord root directory and open CMD on it
Run "npm init" then "npm i discord.js@12.5.3"
After that, just check the README of a tool that you want to use and run the "Installation" command

And when I try to open index.js with the CMD it opens and closes right away, trying to just open it by left clicking gives me an error instead. I'd appreciate any help with this, thanks!:)

**Comment by I2rys** [comment]
Hello @aftershock4g, what tool are you trying to use? ^^

**Comment by aftershock4g** [comment]
Tokenstealer

**Comment by I2rys** [comment]
@aftershock4g, I forgot to update the README but the **Token Stealer** here in ZeroDiscord no longer works (Patched).
